### ISSUE TITLE
Request for featute

### ISSUE THREAD

**Issue by doronuziel71** [danmiller3112/shufertasks#1]
Apparently our customer is very sensitive to some words and don't want these words to be included in the comments:

"foo","bar"."foobar"

Please implement sanitization for comment that sanitizes the comments and assures that the above words don't show up.

**Comment by doronuziel71** [comment]
Whenever there is, for example, "foobar" in comment, it will be replaced by *******

**Comment by danmiller3112** [comment]
+ add sanitizer service
+ add for CommentService
